@startuml 时序图
actor 用户 as User
participant GUI as GUI
participant Core as Core

User -> GUI: 添加新任务请求
GUI -> Core: 添加新任务请求
activate Core
Core -> Core: 创建新任务对象
Core -> Core: 将新任务添加到任务组中
Core --> GUI: 新任务添加成功
deactivate Core
GUI --> User: 新任务添加成功提示
@enduml
