@startuml 部署图

node "用户设备" as UserDevice {
    [Qt Quick]
    [独立实现]
    [Godot]
}

node "Dawdle-Todo 应用" as AppServer {
    [Dawdle-Widget]
    [Dawdle-Godot]
}

node "Dawdlw-Todo 核心" as AppCore{
    [Dawdle-Core]
}

node "PostgreSQL" as PostgreSQL
node "LevelDB" as LevelDB

UserDevice --> AppServer

AppServer --> AppCore

AppCore --> PostgreSQL
AppCore --> LevelDB

@enduml
