name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: creatBuildDir
    - run : mkdir build
    - name: cmake
      run: cmake -G "Ninja" -B build CMakeLists.txt
    - name: changeDir
    - run: cd build
    - name: ninja
      run: ninja
